return {
  require('mjKosmic.plugins.statusline'),
  require('mjKosmic.plugins.colorscheme'),
  require('mjKosmic.plugins.oil'),
  require('mjKosmic.plugins.telescope'),
  require('mjKosmic.plugins.treesitter'),
  require('mjKosmic.plugins.whichkey'),
  require('mjKosmic.plugins.gitsigns'),
  require('mjKosmic.plugins.comment'),
  require('mjKosmic.plugins.sleuth'),
  require('mjKosmic.plugins.cmp'),
  require('mjKosmic.plugins.lspconfig'),
  require('mjKosmic.plugins.mason'),
  require('mjKosmic.plugins.xcodebuild'),
  require('mjKosmic.plugins.dressing'),
}
